# Generated by Django 4.2.14 on 2025-09-11 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Secretary', 'Secretary')], default='Secretary', max_length=9)),
                ('profile_picture', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('discontinued', 'discontinued')], default='active', max_length=12)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('size', models.CharField(max_length=50)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('stock', models.IntegerField(default=0)),
                ('qr_code', models.BinaryField(default=b'')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('sms_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('sales_summary_daily', 'sales_summary_daily'), ('sales_summary_weekly', 'sales_summary_weekly'), ('stock_alert', 'stock_alert'), ('pricing_alert', 'pricing_alert')], max_length=32)),
                ('demand_level', models.CharField(choices=[('high', 'high'), ('mid', 'mid'), ('low', 'low')], max_length=4)),
                ('message_content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appuser', unique=True)),
            ],
            options={
                'db_table': 'sms',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('or_number', models.CharField(default='', max_length=32)),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('contact_number', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change_given', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('voided', 'voided')], default='completed', max_length=10)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('stock_restored', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.appuser', unique=True)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='ReportProductSummary',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('granularity', models.CharField(max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('filters_json', models.JSONField(blank=True, null=True)),
                ('opening_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('added_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sold_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expired_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_addition_at', models.DateTimeField(blank=True, null=True)),
                ('avg_sell_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sell_through_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg_daily_sales', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('days_of_cover_end', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_stock_flag', models.BooleanField(default=False)),
                ('sms_low_stock_count', models.IntegerField(default=0)),
                ('sms_expiry_count', models.IntegerField(default=0)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('price_action', models.CharField(blank=True, max_length=10, null=True)),
                ('demand_level', models.CharField(blank=True, max_length=4, null=True)),
                ('first_sale_at', models.DateTimeField(blank=True, null=True)),
                ('last_sale_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'report_product_summary',
            },
        ),
        migrations.CreateModel(
            name='StockAddition',
            fields=[
                ('addition_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch_id', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'stock_additions',
                'indexes': [models.Index(fields=['product', 'date_added'], name='idx_sa_product_date'), models.Index(fields=['batch_id'], name='idx_sa_batch')],
            },
        ),
    ]
