# Generated by Django 4.2.14 on 2025-09-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sms_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportproductsummary',
            options={'verbose_name': 'generated_reports', 'verbose_name_plural': 'generated_reports'},
        ),
    ]
