# Generated by Django 4.2.14 on 2025-09-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reportproductsummary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportproductsummary',
            options={'verbose_name': 'generated reports', 'verbose_name_plural': 'generated reports'},
        ),
    ]
