# Generated by Django 4.2 on 2025-09-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_reportproductsummary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('master', 'Master Product'), ('inventory', 'Inventory Product')], default='inventory', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
