# Generated by Django 4.2 on 2025-09-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_product_type_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='is_built_in',
            field=models.BooleanField(default=False, help_text="True if this is a built-in product template, False if it's in inventory"),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
