# Generated by Django 4.2 on 2025-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_product_type_product_is_built_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.AlterField(
            model_name='product',
            name='is_built_in',
            field=models.BooleanField(default=False, help_text='True if this is a built-in product from the master list'),
        ),
    ]
