# Generated by Django 4.2.14 on 2025-09-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_is_built_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
