# Generated by Django 4.2.14 on 2025-09-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_is_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_inventory',
        ),
    ]
