# Generated by Django 4.2.14 on 2025-09-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_unique_constraints_from_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockaddition',
            name='batch_id',
            field=models.CharField(max_length=20),
        ),
    ]
