# Generated by Django 4.2 on 2025-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_stockaddition_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaddition',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
