# Generated by Django 4.2.14 on 2025-09-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_transaction_number'),
        ('core', '0015_alter_sale_product_alter_sale_user'),
    ]

    operations = [
    ]
