# Generated by Django 4.2 on 2025-10-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20250919_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.appuser'),
        ),
    ]
