# Generated by Django 5.2.5 on 2025-10-20 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_sms_product_alter_sms_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appuser'),
        ),
    ]
