# Generated by Django 5.2.5 on 2025-10-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_sms_product_alter_sms_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sms',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='uq_sms_product_user'),
        ),
    ]
