# Generated by Django 5.2.5 on 2025-10-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sms_uq_sms_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockaddition',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockaddition',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='stockaddition',
            index=models.Index(fields=['expiry_date'], name='idx_sa_expiry'),
        ),
    ]
