# Generated by Django 5.2.5 on 2025-11-13 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_appuser_email_appuser_is_active_product_sku_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sms',
            name='uq_sms_product_user',
        ),
        migrations.AlterField(
            model_name='sale',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AddConstraint(
            model_name='sms',
            constraint=models.UniqueConstraint(fields=('product', 'user', 'message_type'), name='uq_sms_product_user_type'),
        ),
    ]
