# Generated by Django 5.2.5 on 2025-11-18 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_actionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRecommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('action', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('elasticity', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('r2', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('confidence', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'pricing_recommendations',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'expires_at'], name='idx_pr_product_expires'), models.Index(fields=['expires_at'], name='idx_pr_expires')],
            },
        ),
    ]
