# Generated by Django 5.2.5 on 2025-11-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_pricing_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_pricing_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
