# Generated by Django 5.2.5 on 2025-11-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_appuser_google_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnotificationsettings',
            name='setting_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
