# Generated by Django 5.2.5 on 2025-11-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_size_to_quantity_unit'),
    ]

    operations = [
    ]
