# Generated by Django 5.2.5 on 2025-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20251120_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
