# Generated by Django 5.2.5 on 2025-11-20 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_appuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
