# Generated by Django 5.2.5 on 2025-11-21 04:00

from django.db import migrations


def remove_index_if_exists(apps, schema_editor):
    """Remove index only if it exists"""
    with schema_editor.connection.cursor() as cursor:
        # Check if index exists in PostgreSQL
        cursor.execute("""
            SELECT indexname 
            FROM pg_indexes 
            WHERE tablename='core_stockaddition' 
            AND indexname='idx_sa_expiry'
        """)
        index_exists = cursor.fetchone() is not None
        
        if index_exists:
            cursor.execute("DROP INDEX IF EXISTS idx_sa_expiry")
        # If index doesn't exist, do nothing (it was already removed)


def reverse_migration(apps, schema_editor):
    """Reverse migration - recreate index if needed"""
    # This is a no-op since we're removing an index
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_stockaddition_expiry_fields'),
    ]

    operations = [
        migrations.RunPython(remove_index_if_exists, reverse_migration),
    ]
