# Generated by Django 5.2.5 on 2025-11-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_stockaddition_expiry_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockaddition',
            name='idx_sa_expiry',
        ),
    ]
