# Generated by Django 5.2.5 on 2025-11-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_product_last_pricing_action_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportproductsummary',
            name='accepted_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
