# Generated by Django 5.2.5 on 2025-11-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_reportproductsummary_accepted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportproductsummary',
            name='expired_qty',
        ),
    ]
