# Generated by Django 5.2.5 on 2025-11-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_reportproductsummary_expired_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='allow_google_login',
        ),
    ]
