# Generated by Django 5.2.5 on 2025-11-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_appuser_allow_google_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportproductsummary',
            name='filters_json',
        ),
    ]
