# Generated by Django 5.2.5 on 2025-11-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_sale_discount_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
