# Generated by Django 5.2.5 on 2025-11-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_sale_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotificationsettings',
            name='pricing_frequency_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='smsnotificationsettings',
            name='pricing_time',
            field=models.CharField(default='08:00', max_length=5),
        ),
    ]
