# Generated by Django 5.2.5 on 2025-12-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_fix_variant_from_name_parentheses'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sms',
            name='uq_sms_product_user_type',
        ),
    ]
