# Generated by Django 5.2.5 on 2025-12-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_sms_uq_sms_product_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaddition',
            name='spoiled',
            field=models.IntegerField(default=0),
        ),
    ]
