# Generated by Django 5.2.5 on 2025-12-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_update_kilo_to_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='void_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
