# Generated by Django 5.2.5 on 2025-12-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_appuser_google_email'),
        ('core', '0030_rename_size_to_quantity_unit'),
        ('core', '0037_remove_stockaddition_idx_sa_expiry'),
        ('core', '0041_add_pricing_fields_to_sms_notification_settings'),
        ('core', '0043_normalize_product_name_variant'),
        ('core', '0052_add_void_reason_to_sale'),
    ]

    operations = [
    ]
