# Generated by Django 5.2.5 on 2025-12-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20251209_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnotificationsettings',
            name='pricing_frequency_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='smsnotificationsettings',
            name='pricing_time',
            field=models.CharField(default='08:00', max_length=5),
        ),
        migrations.CreateModel(
            name='PriceChangeHistory',
            fields=[
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.CharField(choices=[('stock_out', 'Stock Out'), ('no_sales', 'No Sales'), ('high_demand', 'High Demand'), ('low_demand', 'Low Demand'), ('seasonal', 'Seasonal Adjustment'), ('cost_change', 'Cost Change'), ('competitor', 'Competitor Pricing'), ('manual', 'Manual Adjustment'), ('ai_recommendation', 'AI Recommendation')], max_length=20)),
                ('reason_details', models.TextField(blank=True, null=True)),
                ('demand_before', models.DecimalField(blank=True, decimal_places=2, help_text='Average daily sales before change', max_digits=10, null=True)),
                ('demand_after', models.DecimalField(blank=True, decimal_places=2, help_text='Average daily sales after change', max_digits=10, null=True)),
                ('stock_level', models.DecimalField(blank=True, decimal_places=2, help_text='Stock level at time of change', max_digits=10, null=True)),
                ('margin_of_error', models.DecimalField(blank=True, decimal_places=4, help_text='Prediction margin of error', max_digits=6, null=True)),
                ('service_type', models.CharField(blank=True, help_text='Type of service/analysis used', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'price_change_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='idx_pch_product_date')],
            },
        ),
    ]
