# Generated by Django 5.2.5 on 2025-12-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_price_change_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaddition',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockaddition',
            name='update_product_price',
            field=models.BooleanField(default=False),
        ),
    ]
