# Generated by Django 5.2.5 on 2025-12-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_add_price_to_stock_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='fifo_breakdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
