# Generated by Django 5.2.5 on 2026-01-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_add_fifo_breakdown_to_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotificationsettings',
            name='master_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
