# Generated by Django 5.2.5 on 2025-09-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('variant', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
                ('date_added', models.DateField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockAddition',
            fields=[
                ('addition_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_id', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('box_quantity', models.IntegerField(default=0, help_text='Number of boxes added')),
                ('date_added', models.DateField()),
                ('remaining_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'stock_additions',
                'managed': False,
            },
        ),
    ]
