"""
Django settings for stockwise_py project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p6rl(ixvtifc+3f3m^%%!#3%k8pk$=jacsu8oygugbf0x+fxw*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.206', '127.0.0.1', 'localhost', '172.20.10.4', '0.0.0.0', 'da443ad746d5.ngrok-free.app', 'e8a6825b9d6a.ngrok-free.app', '.ngrok-free.app']

# Additional CSRF settings for ngrok
CSRF_COOKIE_SECURE = False  # Allow non-HTTPS cookies for development
CSRF_COOKIE_SAMESITE = 'Lax'  # More permissive SameSite policy
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for CSRF tokens
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access to CSRF token
CSRF_TRUSTED_ORIGINS = [
    'https://da443ad746d5.ngrok-free.app',
    'https://e8a6825b9d6a.ngrok-free.app',
    'https://e8a6825b9d6a.ngrok-free.app/',
    'https://da443ad746d5.ngrok-free.app/',
    'https://e8a6825b9d6a.ngrok-free.app',
    'https://da443ad746d5.ngrok-free.app',
    'https://*.ngrok-free.app',  # Wildcard for all ngrok URLs
    'https://*.ngrok.app',  # Alternative ngrok domain
]

# Temporary workaround for ngrok CSRF issues
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'django_crontab',
    'stockwise_qr.qrstock',
]

MIDDLEWARE = [
    'core.maintenance.MaintenanceModeMiddleware',  # TC-043: Maintenance mode
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Disabled for ngrok development
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# NOTE: CSRF middleware is disabled for ngrok development
# Re-enable 'django.middleware.csrf.CsrfViewMiddleware' for production

ROOT_URLCONF = 'stockwise_py.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.parent / 'templates',  # Points to C:\Users\Orly\stockwise\templates
            BASE_DIR / 'templates',         # Points to C:\Users\Orly\stockwise\stockwise_py\templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stockwise_py.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR.parent / 'static',  # Points to C:\Users\Orly\stockwise\static
    BASE_DIR / 'static',         # Points to C:\Users\Orly\stockwise\stockwise_py\static
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Ensure static files are only served from the static directories
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# iProg SMS API credentials – configured via env vars
# Get your API token from: https://sms.iprogtech.com/
IPROG_API_TOKEN = os.getenv('IPROG_API_TOKEN', 'ca42e08b40ba51019938dca6599f28b5a9605acd')
IPROG_SENDER_ID = os.getenv('IPROG_SENDER_ID', 'STOCKWISE')  # Custom sender name (max 11 characters)
# Route selector for iProg (0 or 1). We'll switch to 1 for delivery testing.
IPROG_SMS_PROVIDER = int(os.getenv('IPROG_SMS_PROVIDER', '1'))

# Admin phone number (Philippines local format without +63)
ADMIN_PHONE = os.getenv('ADMIN_PHONE', '9630675254')

CRONJOBS = [
    # Daily sales SMS at 20:00 (8:00 PM) server local time
    ('0 20 * * *', 'django.core.management.call_command', ['send_notifications', '--type=daily_sales']),
    # Low stock alerts every 6 hours (6 AM, 12 PM, 6 PM, 12 AM)
    ('0 6,12,18,0 * * *', 'django.core.management.call_command', ['send_notifications', '--type=low_stock']),
    # AI Pricing recommendations automatically every 3 days at 8 PM
    ('0 20 */3 * *', 'django.core.management.call_command', ['send_auto_pricing']),
]

# CSRF Configuration for ngrok
CSRF_TRUSTED_ORIGINS = [
    # Trust any rotating ngrok subdomain
    'https://c59af87671d6.ngrok-free.app',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://localhost:8000',
    'https://127.0.0.1:8000',
]

# Additional settings for ngrok compatibility
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '45689adbba85.ngrok-free.app',
    'da443ad746d5.ngrok-free.app',
    '.ngrok-free.app',  # Allow all ngrok subdomains
    '.ngrok.io',        # Allow legacy ngrok domains
]

# Disable HTTPS redirect for ngrok
SECURE_SSL_REDIRECT = False

# TC-043: Maintenance mode (set to True to enable)
# Can also be controlled via MAINTENANCE_MODE environment variable
MAINTENANCE_MODE = False

# SMS Configuration for IPROG SMS API
# NOTE: IPROG SMS currently does NOT support custom sender IDs
# All messages use system sender route (sender ID is ignored by API)
IPROG_SENDER_ID = 'IPROGSMS'  # API sender ID (will work when iProg supports custom IDs)
IPROG_SMS_ADMIN_PHONE = '09630675254'  # Admin phone for SMS notifications
SMS_APP_NAME = 'STOCKWISE'  # App name displayed in message content

# IMPORTANT: Set your IPROG API token as environment variable or here
# IPROG_API_TOKEN = 'your_token_here'  # Get from https://sms.iprogtech.com
