"""
Django settings for stockwise_py project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import ssl
import certifi

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
ssl._create_default_https_context = ssl.create_default_context(cafile=certifi.where())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p6rl(ixvtifc+3f3m^%%!#3%k8pk$=jacsu8oygugbf0x+fxw*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allowed hosts for ngrok and local development
ALLOWED_HOSTS = [
    '192.168.1.206',
    '127.0.0.1',
    'localhost',
    '172.20.10.4',
    '0.0.0.0',
    # Specific ngrok URLs (add new ones here)
    'da443ad746d5.ngrok-free.app',
    'e8a6825b9d6a.ngrok-free.app',
    'c59af87671d6.ngrok-free.app',
    '45689adbba85.ngrok-free.app',
    '251c03b3a516.ngrok-free.app',
    '8ad38ee8cba3.ngrok-free.app',  # Current ngrok URL
    '.ngrok-free.app',  # Wildcard for all ngrok-free.app subdomains
    '.ngrok.io',        # Legacy ngrok domains
]

# Tell Django to trust reverse proxy headers from ngrok so scheme/host are correct
# This ensures request.build_absolute_uri uses https when accessed via ngrok
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Additional CSRF settings for ngrok
CSRF_COOKIE_SECURE = False  # Allow non-HTTPS cookies for development
CSRF_COOKIE_SAMESITE = 'Lax'  # More permissive SameSite policy
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for CSRF tokens
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access to CSRF token

# CSRF trusted origins for ngrok
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://localhost:8000',
    'https://127.0.0.1:8000',
    # Specific ngrok URLs (add new ones here with https:// prefix)
    'https://da443ad746d5.ngrok-free.app',
    'https://e8a6825b9d6a.ngrok-free.app',
    'https://c59af87671d6.ngrok-free.app',
    'https://45689adbba85.ngrok-free.app',
    'https://b88dea3d7031.ngrok-free.app',
    'https://c3d95c4375a7.ngrok-free.app',
    'https://251c03b3a516.ngrok-free.app',
    'https://8ad38ee8cba3.ngrok-free.app',  # Current ngrok URL
    'https://*.ngrok-free.app',  # Wildcard for all ngrok URLs
    'https://*.ngrok.app',        # Alternative ngrok domain
    'https://*.ngrok.io',         # Legacy ngrok domains
]

# Temporary workaround for ngrok CSRF issues
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'django_crontab',
    'stockwise_qr.qrstock',
]

MIDDLEWARE = [
    'core.maintenance.MaintenanceModeMiddleware',  # TC-043: Maintenance mode
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Disabled for ngrok development
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# NOTE: CSRF middleware is disabled for ngrok development
# Re-enable 'django.middleware.csrf.CsrfViewMiddleware' for production

ROOT_URLCONF = 'stockwise_py.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.parent / 'templates',  # Points to C:\Users\Orly\stockwise\templates
            BASE_DIR / 'templates',         # Points to C:\Users\Orly\stockwise\stockwise_py\templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stockwise_py.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Ensure static files are only served from the static directories
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'  # Points to C:\Users\Orly\stockwise\media

FRUIT_MASTER_DIR = MEDIA_ROOT / 'builtins'
FRUIT_MASTER_PATH = str(FRUIT_MASTER_DIR / 'fruit_master_full.csv')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# iProg SMS API credentials – configured via env vars
# Get your API token from: https://sms.iprogtech.com/
IPROG_API_TOKEN = os.getenv('IPROG_API_TOKEN', 'ca42e08b40ba51019938dca6599f28b5a9605acd')
IPROG_SENDER_ID = os.getenv('IPROG_SENDER_ID', 'STOCKWISE')  # Custom sender name (max 11 characters)
# Route selector for iProg (0 or 1). We'll switch to 1 for delivery testing.
IPROG_SMS_PROVIDER = int(os.getenv('IPROG_SMS_PROVIDER', '1'))

# Admin phone number (Philippines local format without +63)
ADMIN_PHONE = os.getenv('ADMIN_PHONE', '9630675254')

CRONJOBS = [
    # Daily sales SMS at 20:00 (8:00 PM) server local time
    ('0 20 * * *', 'django.core.management.call_command', ['send_notifications', '--type=daily_sales']),
    # Low stock alerts DISABLED - prevent excessive SMS usage
    # ('0 6,12,18,0 * * *', 'django.core.management.call_command', ['send_notifications', '--type=low_stock']),
    # AI Pricing recommendations automatically every 3 days at 8 PM
    ('0 20 */3 * *', 'django.core.management.call_command', ['send_auto_pricing']),
    # Daily backup at 2:00 AM
    ('0 2 * * *', 'django.core.management.call_command', ['backup_system']),
    # Cleanup old backups at 3:00 AM (keep last 7 days)
    ('0 3 * * *', 'django.core.management.call_command', ['cleanup_old_backups', '--keep-days=7']),
]

# Auto-backup settings
AUTO_BACKUP_ENABLED = True  # Enable automatic backups before critical operations

# Disable HTTPS redirect for ngrok
SECURE_SSL_REDIRECT = False

# Allow embedding application pages/PDF previews in same-origin iframes
X_FRAME_OPTIONS = 'SAMEORIGIN'

# TC-043: Maintenance mode (set to True to enable)
# Can also be controlled via MAINTENANCE_MODE environment variable
MAINTENANCE_MODE = False

# SMS Configuration for IPROG SMS API
# NOTE: IPROG SMS currently does NOT support custom sender IDs
# All messages use system sender route (sender ID is ignored by API)
IPROG_SENDER_ID = 'IPROGSMS'  # API sender ID (will work when iProg supports custom IDs)
IPROG_SMS_ADMIN_PHONE = '09630675254'  # Admin phone for SMS notifications
SMS_APP_NAME = 'STOCKWISE'  # App name displayed in message content

# IMPORTANT: Set your IPROG API token as environment variable or here

# ========== THERMAL PRINTER SETTINGS ==========
# Thermal Printer Configuration (58mm portable thermal printer)
# Connection Types: 'usb', 'serial', 'bluetooth', 'network', 'windows'
# 
# IMPORTANT: Most USB thermal printers appear as COM ports on Windows.
# Use 'serial' connection type with the COM port (e.g., COM3, COM4).
# Use 'windows' if your printer appears in "Print queues" but not as a COM port.
# Use 'usb' only if your printer connects as a direct USB HID device (less common).
#
# Quick setup: Run 'python setup_thermal_printer.py' to auto-detect your printer
# For POS58 Printer that appears in Print queues, use 'windows' mode:
THERMAL_PRINTER_TYPE = os.getenv('THERMAL_PRINTER_TYPE', 'windows')  # Default: windows (for printers in Print queues)

# USB Connection Settings (if using 'usb' connection type - less common)
# Note: vendor_id and product_id are required for direct USB connection
# Find your printer's VID/PID by connecting it and checking Device Manager (Windows)
# or using 'lsusb' command (Linux)
# Example: VID_04F9&PID_2040 means vendor_id=0x04f9, product_id=0x2040

# Serial/USB Serial Connection Settings (if using 'serial' connection type - most common for USB)
# This is the recommended method for USB thermal printers on Windows
# The printer will appear as a COM port (e.g., COM3, COM4, COM5)
THERMAL_PRINTER_PORT = os.getenv('THERMAL_PRINTER_PORT', 'COM3')  # Windows: COM3, COM4, etc. Linux: /dev/ttyUSB0, /dev/ttyACM0
THERMAL_PRINTER_BAUDRATE = int(os.getenv('THERMAL_PRINTER_BAUDRATE', 9600))  # Common baudrates: 9600, 19200, 38400, 115200

# Network Printer Settings (if using network connection)
THERMAL_PRINTER_HOST = os.getenv('THERMAL_PRINTER_HOST', '192.168.1.100')
THERMAL_PRINTER_NETWORK_PORT = int(os.getenv('THERMAL_PRINTER_NETWORK_PORT', 9100))

# Windows Printer Settings (if using Windows print spooler - for printers that appear in Print queues)
# Use this if your printer shows up in Device Manager under "Print queues" but not under "Ports (COM & LPT)"
# The printer name should match exactly as it appears in Windows Settings → Printers & scanners
THERMAL_PRINTER_NAME = os.getenv('THERMAL_PRINTER_NAME', 'POS58 Printer')
# IPROG_API_TOKEN = 'your_token_here'  # Get from https://sms.iprogtech.com

# ========== GOOGLE AUTH SETTINGS ==========
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
GOOGLE_OAUTH_SCOPES = ['openid', 'email', 'profile']
GOOGLE_AUTHORIZATION_ENDPOINT = 'https://accounts.google.com/o/oauth2/v2/auth'
GOOGLE_TOKEN_ENDPOINT = 'https://oauth2.googleapis.com/token'
GOOGLE_REDIRECT_BASE = os.getenv('GOOGLE_REDIRECT_BASE', '')  # e.g., 'http://127.0.0.1:8000'

# Allow only the temporary admin+secretary Google accounts unless overridden
GOOGLE_ALLOWED_ACCOUNTS = {
    os.getenv('GOOGLE_ADMIN_EMAIL', 'otmedina.chmsu@gmail.com').lower(): {
        'role': 'Admin',
        'username': os.getenv('GOOGLE_ADMIN_USERNAME', 'admin'),
    },
    os.getenv('GOOGLE_SECRETARY_EMAIL', 'orly.m8xz@gmail.com').lower(): {
        'role': 'Secretary',
        'username': os.getenv('GOOGLE_SECRETARY_USERNAME', 'secretary'),
    },
}

# ========== EMAIL / TWO-FACTOR SETTINGS ==========
# Default to SMTP backend (production-safe). Override via EMAIL_BACKEND env var if needed.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
# Use STARTTLS by default (change via env vars if needed)
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@stockwise.local')

TWO_FACTOR_CODE_EXPIRY_MINUTES = int(os.getenv('TWO_FACTOR_CODE_EXPIRY_MINUTES', '2'))
TWO_FACTOR_MAX_ATTEMPTS = int(os.getenv('TWO_FACTOR_MAX_ATTEMPTS', '5'))

# SSL Context for email (production-ready)
# In production, use proper certificate verification (default)
# Only use unverified context for development/testing if explicitly set
# Django's SMTP backend will use proper SSL verification by default when EMAIL_USE_SSL=True
# This ensures emails work with proper certificates and won't be blocked by antivirus/firewall
if os.getenv('EMAIL_SSL_VERIFY', 'true').lower() == 'false':
    # Only for development/testing - NOT recommended for production
    # WARNING: This bypasses SSL certificate verification and is insecure
    import ssl
    EMAIL_SSL_CERT_REQS = ssl.CERT_NONE
    # Create a custom SSL context only if needed for development
    # In production, Django will use default SSL context with proper verification
else:
    # Production: Use proper SSL certificate verification (default)
    # Django's SMTP backend automatically verifies certificates when EMAIL_USE_SSL=True
    # No custom SSL context needed - Django handles it properly
    pass
