"""
Django settings for stockwise_py project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import json
from dotenv import load_dotenv
import ssl
import certifi
import bcrypt

# Monkeypatch bcrypt for passlib compatibility if needed
if not hasattr(bcrypt, "__about__"):
    class About:
        __version__ = bcrypt.__version__
    bcrypt.__about__ = About()

try:
    import dj_database_url  # Optional; used when available
    _HAS_DJ_DATABASE_URL = True
except Exception:
    dj_database_url = None
    _HAS_DJ_DATABASE_URL = False
try:
    import whitenoise  # noqa: F401
    _HAS_WHITENOISE = True
except Exception:
    _HAS_WHITENOISE = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
ssl._create_default_https_context = ssl.create_default_context(cafile=certifi.where())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable if available (for production), otherwise use default (for development)
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-p6rl(ixvtifc+3f3m^%%!#3%k8pk$=jacsu8oygugbf0x+fxw*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'false').lower() == 'true'
MAINTENANCE_MODE = os.getenv('MAINTENANCE_MODE', 'false').lower() == 'true'

# Allowed hosts for ngrok and local development
ALLOWED_HOSTS = [
    '192.168.1.206',
    '127.0.0.1',
    'localhost',
    '172.20.10.4',
    '0.0.0.0',
    # Specific ngrok URLs (add new ones here)
    'da443ad746d5.ngrok-free.app',
    'e8a6825b9d6a.ngrok-free.app',
    'c59af87671d6.ngrok-free.app',
    '45689adbba85.ngrok-free.app',
    '251c03b3a516.ngrok-free.app',
    '8ad38ee8cba3.ngrok-free.app',  # Current ngrok URL
    '.ngrok-free.app',  # Wildcard for all ngrok-free.app subdomains
    '.ngrok.io',        # Legacy ngrok domains
    '.ondigitalocean.app',
    '.digitaloceansites.com',
    # Render hosting
    '.onrender.com',
    '.render.com',
]

# Tell Django to trust reverse proxy headers from ngrok so scheme/host are correct
# This ensures request.build_absolute_uri uses https when accessed via ngrok
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Additional CSRF settings for ngrok
CSRF_COOKIE_SECURE = False  # Allow non-HTTPS cookies for development
CSRF_COOKIE_SAMESITE = 'Lax'  # More permissive SameSite policy
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for CSRF tokens
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access to CSRF token

# CSRF trusted origins for ngrok
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://localhost:8000',
    'https://127.0.0.1:8000',
    # Specific ngrok URLs (add new ones here with https:// prefix)
    'https://da443ad746d5.ngrok-free.app',
    'https://e8a6825b9d6a.ngrok-free.app',
    'https://c59af87671d6.ngrok-free.app',
    'https://45689adbba85.ngrok-free.app',
    'https://b88dea3d7031.ngrok-free.app',
    'https://c3d95c4375a7.ngrok-free.app',
    'https://251c03b3a516.ngrok-free.app',
    'https://8ad38ee8cba3.ngrok-free.app',  # Current ngrok URL
    'https://*.ngrok-free.app',  # Wildcard for all ngrok URLs
    'https://*.ngrok.app',        # Alternative ngrok domain
    'https://*.ngrok.io',         # Legacy ngrok domains
    'https://*.ondigitalocean.app',
    'https://*.digitaloceansites.com',
    # Render hosting
    'https://*.onrender.com',
    'https://*.render.com',
]

# Temporary workaround for ngrok CSRF issues
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'core',
    'django_crontab',
    'stockwise_qr.qrstock',
]
if not _HAS_WHITENOISE:
    INSTALLED_APPS = [app for app in INSTALLED_APPS if app != 'whitenoise.runserver_nostatic']

MIDDLEWARE = [
    'core.maintenance.MaintenanceModeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.JSONErrorMiddleware',  # Ensure API errors are JSON
    'core.maintenance.AuditMiddleware',
    'core.maintenance.FriendlyErrorMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if not _HAS_WHITENOISE:
    MIDDLEWARE = [m for m in MIDDLEWARE if m != 'whitenoise.middleware.WhiteNoiseMiddleware']
if os.getenv('DISABLE_CSRF', 'false').lower() == 'true':
    MIDDLEWARE = [m for m in MIDDLEWARE if m != 'django.middleware.csrf.CsrfViewMiddleware']

# NOTE: CSRF middleware is disabled for ngrok development
# Re-enable 'django.middleware.csrf.CsrfViewMiddleware' for production

ROOT_URLCONF = 'stockwise_py.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.parent / 'templates',  # Points to C:\Users\Orly\stockwise\templates
            BASE_DIR / 'templates',         # Points to C:\Users\Orly\stockwise\stockwise_py\templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stockwise_py.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,  # Increase timeout to 20 seconds to prevent "database is locked" errors
        }
    }
}

# Override database from DATABASE_URL if provided (e.g., DigitalOcean Managed DB)
_db_url = (os.getenv('DATABASE_URL') or '').strip()
if _HAS_DJ_DATABASE_URL:
    try:
        # Only attempt parse when value looks like a real URL (scheme present)
        if _db_url and not _db_url.startswith('${'):
            DATABASES['default'] = dj_database_url.config(default=_db_url, conn_max_age=600)
    except Exception:
        # Fallback to SQLite if DATABASE_URL is invalid during build
        pass


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'stockwise_py' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
WHITENOISE_USE_FINDERS = True

# Ensure static files are only served from the static directories
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' if _HAS_WHITENOISE else 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Media files (user uploads)
# Use persistent media directory from environment variable if set (for hosting)
# Otherwise use project directory (for local development)
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media')))
# Don't create directory at import time - let Django/application handle it when needed
# This prevents permission errors in production environments like Render

BACKUPS_DIR = Path(os.getenv('BACKUPS_DIR') or (BASE_DIR / 'backups'))

FRUIT_MASTER_DIR = MEDIA_ROOT / 'builtins'
FRUIT_MASTER_PATH = str(FRUIT_MASTER_DIR / 'fruit_master_full.csv')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Disable request audit logs from middleware by default
AUDIT_MIDDLEWARE_ENABLED = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session security: expire login sessions after 1 day
SESSION_COOKIE_AGE = 60 * 60 * 24

# Hosting maintenance mode toggle
# Set environment variable MAINTENANCE_MODE=true to enable via env
MAINTENANCE_MODE = True

# iProg SMS API credentials – configured via env vars
# Get your API token from: https://sms.iprogtech.com/
IPROG_API_TOKEN = os.getenv('IPROG_API_TOKEN', '')
IPROG_SENDER_ID = os.getenv('IPROG_SENDER_ID', 'STOCKWISE')  # Custom sender name (max 11 characters)
# Route selector for iProg (0 or 1). We'll switch to 1 for delivery testing.
IPROG_SMS_PROVIDER = int(os.getenv('IPROG_SMS_PROVIDER', '1'))
IPROG_SENDER_NAME = os.getenv('IPROG_SENDER_NAME', 'kaprets')

CRONJOBS = [
    ('*/5 * * * *', 'django.core.management.call_command', ['send_notifications', '--type=daily_sales']),
    ('0 2 * * *', 'django.core.management.call_command', ['backup_system']),
    ('0 3 * * *', 'django.core.management.call_command', ['cleanup_old_backups', '--keep-days=7']),
]

# Auto-backup settings
AUTO_BACKUP_ENABLED = True  # Enable automatic backups before critical operations

# Disable HTTPS redirect for ngrok
SECURE_SSL_REDIRECT = False

# Allow embedding application pages/PDF previews in same-origin iframes
X_FRAME_OPTIONS = 'SAMEORIGIN'

# TC-043: Maintenance mode (set to True to enable)
# Can also be controlled via MAINTENANCE_MODE environment variable
MAINTENANCE_MODE = False

# SMS Configuration for IPROG SMS API
# NOTE: IPROG SMS currently does NOT support custom sender IDs
# All messages use system sender route (sender ID is ignored by API)
IPROG_SENDER_ID = 'IPROGSMS'  # API sender ID (will work when iProg supports custom IDs)
SMS_APP_NAME = 'STOCKWISE'  # App name displayed in message content

# IMPORTANT: Set your IPROG API token as environment variable or here

# ========== THERMAL PRINTER SETTINGS ==========
# Thermal Printer Configuration (58mm portable thermal printer)
# Connection Types: 'usb', 'serial', 'bluetooth', 'network', 'windows'
# 
# IMPORTANT: Most USB thermal printers appear as COM ports on Windows.
# Use 'serial' connection type with the COM port (e.g., COM3, COM4).
# Use 'windows' if your printer appears in "Print queues" but not as a COM port.
# Use 'usb' only if your printer connects as a direct USB HID device (less common).
#
# Quick setup: Run 'python setup_thermal_printer.py' to auto-detect your printer
# For POS58 Printer that appears in Print queues, use 'windows' mode:
THERMAL_PRINTER_TYPE = os.getenv('THERMAL_PRINTER_TYPE', 'windows')  # Default: windows (for printers in Print queues)

# USB Connection Settings (if using 'usb' connection type - less common)
# Note: vendor_id and product_id are required for direct USB connection
# Find your printer's VID/PID by connecting it and checking Device Manager (Windows)
# or using 'lsusb' command (Linux)
# Example: VID_04F9&PID_2040 means vendor_id=0x04f9, product_id=0x2040

# Serial/USB Serial Connection Settings (if using 'serial' connection type - most common for USB)
# This is the recommended method for USB thermal printers on Windows
# The printer will appear as a COM port (e.g., COM3, COM4, COM5)
THERMAL_PRINTER_PORT = os.getenv('THERMAL_PRINTER_PORT', 'COM3')  # Windows: COM3, COM4, etc. Linux: /dev/ttyUSB0, /dev/ttyACM0
THERMAL_PRINTER_BAUDRATE = int(os.getenv('THERMAL_PRINTER_BAUDRATE', 9600))  # Common baudrates: 9600, 19200, 38400, 115200

# Network Printer Settings (if using network connection)
THERMAL_PRINTER_HOST = os.getenv('THERMAL_PRINTER_HOST', '192.168.1.100')
THERMAL_PRINTER_NETWORK_PORT = int(os.getenv('THERMAL_PRINTER_NETWORK_PORT', 9100))

# Windows Printer Settings (if using Windows print spooler - for printers that appear in Print queues)
# Use this if your printer shows up in Device Manager under "Print queues" but not under "Ports (COM & LPT)"
# The printer name should match exactly as it appears in Windows Settings → Printers & scanners
THERMAL_PRINTER_NAME = os.getenv('THERMAL_PRINTER_NAME', 'POS58 Printer')
# Optional: HTTP print bridge URL; if set, server will POST receipt/test jobs
# IPROG_API_TOKEN = 'your_token_here'  # Get from https://sms.iprogtech.com

GOOGLE_OAUTH_SCOPES = ['openid', 'email', 'profile']
GOOGLE_AUTHORIZATION_ENDPOINT = 'https://accounts.google.com/o/oauth2/v2/auth'
GOOGLE_TOKEN_ENDPOINT = 'https://oauth2.googleapis.com/token'
_GOOGLE_CLIENT_ID = (os.getenv('GOOGLE_CLIENT_ID', '') or '').strip()
_GOOGLE_CLIENT_SECRET = (os.getenv('GOOGLE_CLIENT_SECRET', '') or '').strip()
_GOOGLE_REDIRECT_BASE = (os.getenv('GOOGLE_REDIRECT_BASE', '') or '').strip()
_GOOGLE_CREDENTIALS_FILE = (os.getenv('GOOGLE_CREDENTIALS_FILE', '') or '').strip()
def _clean_val(_s):
    try:
        return (_s or '').replace('`','').replace('"','').replace("'",'').strip()
    except Exception:
        return (_s or '').strip()
if not _GOOGLE_CREDENTIALS_FILE:
    try:
        for _fname in os.listdir(BASE_DIR.parent):
            if _fname.startswith('client_secret_') and _fname.endswith('.json'):
                _GOOGLE_CREDENTIALS_FILE = str((BASE_DIR.parent / _fname).resolve())
                break
    except Exception:
        pass
try:
    if (not _GOOGLE_CLIENT_ID or not _GOOGLE_CLIENT_SECRET) and _GOOGLE_CREDENTIALS_FILE and os.path.exists(_GOOGLE_CREDENTIALS_FILE):
        with open(_GOOGLE_CREDENTIALS_FILE, 'r', encoding='utf-8') as _f:
            _data = json.load(_f)
        _web = _data.get('web') or _data
        _cid = _clean_val(_web.get('client_id') or '')
        _sec = _clean_val(_web.get('client_secret') or '')
        if _cid and _sec:
            _GOOGLE_CLIENT_ID = _cid
            _GOOGLE_CLIENT_SECRET = _sec
        _origins = _web.get('javascript_origins') or []
        if not _GOOGLE_REDIRECT_BASE and isinstance(_origins, list) and _origins:
            _GOOGLE_REDIRECT_BASE = _clean_val(_origins[-1] or '')
except Exception:
    pass
GOOGLE_CLIENT_ID = _clean_val(_GOOGLE_CLIENT_ID)
GOOGLE_CLIENT_SECRET = _clean_val(_GOOGLE_CLIENT_SECRET)
GOOGLE_REDIRECT_BASE = _clean_val(_GOOGLE_REDIRECT_BASE)

# Optional: HTTP print bridge URL; if set, server will POST receipt/test jobs
PRINTER_WEBHOOK_URL = _clean_val(os.getenv('PRINTER_WEBHOOK_URL', ''))

# Allow only the temporary admin+secretary Google accounts unless overridden
GOOGLE_ALLOWED_ACCOUNTS = {
    os.getenv('GOOGLE_ADMIN_EMAIL', 'otmedina.chmsu@gmail.com').lower(): {
        'role': 'Admin',
        'username': os.getenv('GOOGLE_ADMIN_USERNAME', 'admin'),
    },
    os.getenv('GOOGLE_SECRETARY_EMAIL', 'orly.m8xz@gmail.com').lower(): {
        'role': 'Secretary',
        'username': os.getenv('GOOGLE_SECRETARY_USERNAME', 'secretary'),
    },
}

# DATABASE_URL is already handled above at lines 186-194 with proper error handling
# No need to parse it again here

# ========== EMAIL / TWO-FACTOR SETTINGS ==========
# Default to SMTP backend (production-safe). Override via EMAIL_BACKEND env var if needed.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
# Handle EMAIL_PORT gracefully - use default if invalid
try:
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
except (ValueError, TypeError):
    EMAIL_PORT = 587
# Use STARTTLS by default (change via env vars if needed)
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_HOST_USER = _clean_val(os.getenv('EMAIL_HOST_USER', ''))
EMAIL_HOST_PASSWORD = _clean_val(os.getenv('EMAIL_HOST_PASSWORD', '')).replace(' ', '')
EMAIL_SENDER_NAME = _clean_val(os.getenv('EMAIL_SENDER_NAME', ''))
_DEFAULT_FROM = _clean_val(os.getenv('DEFAULT_FROM_EMAIL', ''))
DEFAULT_FROM_EMAIL = (
    _DEFAULT_FROM or (
        f"{EMAIL_SENDER_NAME} <{EMAIL_HOST_USER}>" if EMAIL_SENDER_NAME and EMAIL_HOST_USER else (EMAIL_HOST_USER or 'no-reply@stockwise.local')
    )
)

TWO_FACTOR_CODE_EXPIRY_MINUTES = int(os.getenv('TWO_FACTOR_CODE_EXPIRY_MINUTES', '2'))
TWO_FACTOR_MAX_ATTEMPTS = int(os.getenv('TWO_FACTOR_MAX_ATTEMPTS', '5'))

# Logging configuration for SMS debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'sms_debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'core.sms_service': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.management.commands.send_notifications': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

# SSL Context for email (production-ready)
# In production, use proper certificate verification (default)
# Only use unverified context for development/testing if explicitly set
# Django's SMTP backend will use proper SSL verification by default when EMAIL_USE_SSL=True
# This ensures emails work with proper certificates and won't be blocked by antivirus/firewall
if os.getenv('EMAIL_SSL_VERIFY', 'true').lower() == 'false':
    # Only for development/testing - NOT recommended for production
    # WARNING: This bypasses SSL certificate verification and is insecure
    import ssl
    EMAIL_SSL_CERT_REQS = ssl.CERT_NONE
    # Create a custom SSL context only if needed for development
    # In production, Django will use default SSL context with proper verification
else:
    # Production: Use proper SSL certificate verification (default)
    # Django's SMTP backend automatically verifies certificates when EMAIL_USE_SSL=True
    # No custom SSL context needed - Django handles it properly
    pass
